// ServerLayout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/UserContex";
import { TourGuideProvider } from "./context/tourGuideContext";
import { PlannedTourProvider } from "./context/tourPlanContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ServerLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <TourGuideProvider>
            <PlannedTourProvider>{children}</PlannedTourProvider>
          </TourGuideProvider>
        </UserProvider>
      </body>
    </html>
  );
}
